const videoData = {
  videos: [
    {
      title: "Pregnancy Yoga For Second Trimester",
      category: "medium",
      description:"Pregnancy Yoga For Second Trimester or Third Trimester. A feel-good yoga class for a sore pregnant body and to help keep your body strong for labor.",
      type:"yoga",
      url: "https://www.youtube.com/watch?v=D75ClMK09TA",
    },
    {
      title: "Pregnancy Yoga Third Trimester",
      category: "low",
      description:"Pregnancy Yoga For Third Trimester. Relieve 3rd trimester aches and prepare for labor.",
      type:"yoga",
      url: "https://www.youtube.com/watch?v=Cc_vRDbp7JE",
    },
    {
      title: "Gentle Full Body Class For A Healthy Pregnancy",
      category: "medium",
      description:"This 25 Min prenatal yoga workout for full body & a healthy pregnancy is a part of our 'Prenatal Bliss' program",
      type:"yoga",
      url: "https://www.youtube.com/watch?v=_NP6u3TWlBE",
    },
    {
      title: "Prenatal Yoga For Stress And Anxiety",
      category: "high",
      description:"This video provides pregnancy stress and anxiety relief. Includes pregnancy yoga for anxiety and pregnancy anxiety meditation.",
      type:"yoga",
      url: "https://www.youtube.com/watch?v=YBk-MP5D8CI",
    },
    {
      title: "Prenatal Meditation",
      category: "high",
      description:"This meditation is to deepen your sense of Self love and connection to your developing baby.",
      type:"meditation",
      url: "https://www.youtube.com/watch?v=ZGzLDVUvrqk",
    },
    {
      title: "Mindfulness Pregnancy Yoga Relaxation Techniques",
      category: "high",
      description:"This mindfulness prenatal meditation is the perfect practice to return to during those over-whelming emotional pregnant days. ",
      type:"meditation",
      url: "https://www.youtube.com/watch?v=9SQwSqAQ9UQ",
    },
    {
      title: "Prenatal Meditation for a Healthy Pregnancy",
      category: "high",
      description:"This  prenatal meditation is an awesome way to relax and connect with the soul of your baby.",
      type:"meditation",
      url: "https://www.youtube.com/watch?v=SIwXOj0BOOY",
    },
    {
      title: "Pregnancy Exercises For Easy Delivery",
      category: "medium",
      description:"Prepare your body for an easy vaginal birth or even if you have a c-section.",
      type:"cardio",
      url: "https://www.youtube.com/watch?v=Q6wuhzynBuM",
    },
    {
      title: "Best Pregnancy Stretches",
      category: "easy",
      description:"These are great daily pregnancy stretches (a stretch routine) to keep away pregnancy aches and pains and help pregnancy symptoms.",
      type:"cardio",
      url: "https://www.youtube.com/watch?v=ZZIl3ZwcyRg",
    },
    {
      title: "Easy Exercises for Normal Delivery - Prenatal Exercises",
      category: "low",
      description:"Easy Exercises for Normal Delivery - Prenatal Exercises",
      type:"cardio",
      url: "https://www.youtube.com/watch?v=Eq4uMHzdaI8&list=PLj8hRf1iIiqkVypgG_M8JZ-C7V1XDT8uA",
    },
  ],
}
export default videoData
